"""Начальная схема: срезы стакана, запуски сборщика, аккаунты и настройки

Пять таблиц версии 0.1.0. Ничего из этого ещё не используется приложением:
сборщик появится на этапе 7, вход через EVE SSO — на этапе 9.

Revision ID: 3276dc847fb3
Revises:
Create Date: 2026-08-17 22:54:31.902259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3276dc847fb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requests_made', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('snapshots_written', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'partial', 'aborted')", name=op.f('ck_collection_run_collection_run_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_run'))
    )
    with op.batch_alter_table('collection_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_run_started_at'), ['started_at'], unique=False)

    op.create_table('user_account',
    sa.Column('character_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('character_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_user_account'))
    )
    op.create_table('market_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_key', sa.String(length=16), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('ladder', sa.Text(), nullable=False),
    sa.Column('total_volume', sa.BigInteger(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("side IN ('sell', 'buy')", name=op.f('ck_market_snapshot_market_snapshot_side')),
    sa.ForeignKeyConstraint(['run_id'], ['collection_run.id'], name=op.f('fk_market_snapshot_run_id_collection_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshot'))
    )
    with op.batch_alter_table('market_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_market_snapshot_lookup', ['hub_key', 'type_id', 'side', 'collected_at'], unique=False)

    op.create_table('user_freight_rate',
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('hub_key', sa.String(length=16), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['user_account.character_id'], name=op.f('fk_user_freight_rate_character_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'hub_key', name=op.f('pk_user_freight_rate'))
    )
    op.create_table('user_settings',
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('gas_key', sa.String(length=64), nullable=True),
    sa.Column('n_units', sa.Integer(), nullable=True),
    sa.Column('structure', sa.String(length=16), nullable=True),
    sa.Column('gde_level', sa.Integer(), nullable=True),
    sa.Column('broker_fee', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('collateral_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sell_only', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['user_account.character_id'], name=op.f('fk_user_settings_character_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_user_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('user_freight_rate')
    with op.batch_alter_table('market_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_market_snapshot_lookup')

    op.drop_table('market_snapshot')
    op.drop_table('user_account')
    with op.batch_alter_table('collection_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_run_started_at'))

    op.drop_table('collection_run')
    # ### end Alembic commands ###
