"""istoriya sdelok

Revision ID: 594f2e77bc72
Revises: 5d83733279a5
Create Date: 2026-08-19 01:02:11.505684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594f2e77bc72'
down_revision: Union[str, Sequence[str], None] = '5d83733279a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('average', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('highest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('lowest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_history')),
    sa.UniqueConstraint('region_id', 'type_id', 'date', name=op.f('uq_market_history_region_id_type_id_date'))
    )
    op.create_table('market_history_state',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('last_modified', sa.String(length=64), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('region_id', 'type_id', name=op.f('pk_market_history_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_history_state')
    op.drop_table('market_history')
    # ### end Alembic commands ###
