"""ETag среза: условные запросы к ESI

Ответ 304 стоит 1 токен вместо 2 (docs/ESI.md §2), поэтому ETag предыдущего
ответа сохраняется и уходит обратно в заголовке If-None-Match.

Revision ID: 5d83733279a5
Revises: 3276dc847fb3
Create Date: 2026-08-17 23:07:28.204260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d83733279a5'
down_revision: Union[str, Sequence[str], None] = '3276dc847fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etag', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_snapshot', schema=None) as batch_op:
        batch_op.drop_column('etag')

    # ### end Alembic commands ###
